{{- with $.Values.cluster}}
{{if .certificates.self_signed}}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  selfSigned: {}
---
{{- end}}

{{- with .certificates}}

{{- with .ca_certificate}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.cluster.namespace}}
spec:
  secretName: {{ .secret_name }}
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    - {{$.Values.ingress.elasticsearch.host}}    
    - {{$.Values.elasticsearch.services.http.name}}
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    - {{$.Values.ingress.kibana.host}}
    - {{$.Values.kibana.services.http.name}}
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    - {{$.Values.ingress.apm.host}}
    - {{$.Values.apm.services.http.name}}
    - {{$.Values.apm.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.apm.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
  issuerRef:      
    kind: {{.issuer_kind}}
    name: {{.issuer_name}}
---
{{- end}}

{{- with .certificate}}

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata: 
  name: ca-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  ca:
    secretName: elasticsearch-cert-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{$.Values.cluster.namespace}}
spec:
  secretName: {{ .secret_name }}
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    - {{$.Values.ingress.elasticsearch.host}}    
    - {{$.Values.elasticsearch.services.http.name}}
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    - {{$.Values.ingress.kibana.host}}
    - {{$.Values.kibana.services.http.name}}
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    - {{$.Values.ingress.apm.host}}
    - {{$.Values.apm.services.http.name}}
    - {{$.Values.apm.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.apm.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ca-issuer

{{- end}}

{{- end}}
{{- end}}