---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elasticsearch-cert-ca
  namespace: {{$.Values.cluster.namespace}}
spec:
  secretName: elasticsearch-cert-ca
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    - elasticsearch-http
    - elasticsearch-http.default.svc
    - elasticsearch-http.default.svc.cluster.local
    - kibana-http
    - kibana-http.default.svc
    - kibana-http.default.svc.cluster.local
  issuerRef:
    # kind: ClusterIssuer
    # name: letsencrypt-staging
    kind: Issuer
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata: 
  name: ca-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  ca:
    secretName: elasticsearch-cert-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: {{$.Values.cluster.namespace}}
spec:
  secretName: elasticsearch-cert
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    - elasticsearch-http
    - elasticsearch-http.default.svc
    - elasticsearch-http.default.svc.cluster.local
    - kibana-http
    - kibana-http.default.svc
    - kibana-http.default.svc.cluster.local
  issuerRef:
    # kind: ClusterIssuer
    # name: letsencrypt-staging
    kind: Issuer
    name: ca-issuer