---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elasticsearch-cert-ca
  namespace: {{$.Values.cluster.namespace}}
spec:
  secretName: elasticsearch-cert-ca
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    {{- if $.Values.ingress.elasticsearch.host }}
    - {{$.Values.ingress.elasticsearch.host}}
    {{- end}}
    - {{$.Values.elasticsearch.services.http.name}}
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    {{- if $.Values.ingress.kibana.host }}
    - {{$.Values.ingress.kibana.host}}
    {{- end}}
    - {{$.Values.kibana.services.http.name}}
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
  issuerRef:  
    {{- if $.Values.cluster.certificate.cluster_issuer}}
    kind: ClusterIssuer
    name: {{$.Values.cluster.certificate.cluster_issuer}}
    {{- end}}
    {{- if $.Values.cluster.certificate.issuer}}
    kind: Issuer
    name: {{$.Values.cluster.certificate.issuer}}
    {{- end}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata: 
  name: ca-issuer
  namespace: {{$.Values.cluster.namespace}}
spec:
  ca:
    secretName: elasticsearch-cert-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: {{$.Values.cluster.namespace}}
spec:
  secretName: elasticsearch-cert
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  commonName: elastic
  dnsNames:
    {{- if $.Values.ingress.elasticsearch.host }}
    - {{$.Values.ingress.elasticsearch.host}}
    {{- end}}
    - {{$.Values.elasticsearch.services.http.name}}
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.elasticsearch.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
    {{- if $.Values.ingress.kibana.host }}
    - {{$.Values.ingress.kibana.host}}
    {{- end}}
    - {{$.Values.kibana.services.http.name}}
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc
    - {{$.Values.kibana.services.http.name}}.{{$.Values.cluster.namespace}}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ca-issuer