{{- if $.Values.ingress }}
{{with $.Values.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: {{$.Values.cluster.namespace}}
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/protocol: https
spec:
  rules:
  # {{- if $.Values.ingress.elasticsearch.host }}
  # - host: {{$.Values.ingress.elasticsearch.host}}
  - host: ty-elastic.openlogic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{$.Values.elasticsearch.services.http.name}}
          servicePort: 9200
  # {{- end}}
  # {{- if $.Values.ingress.kibana.host }}
  # - host: {{$.Values.ingress.kibana.host}}
  - host: ty-kibana.openlogic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{$.Values.kibana.services.http.name}}
          servicePort: 5601
  # {{- end}}
{{- end }}
{{- end }}