{{- with $.Values.elasticsearch.services.discovery }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ .name }}
  namespace: {{$.Values.cluster.namespace}}
spec:
  clusterIP: None
  ports:
  {{- range .ports }}
  - name: {{.name}}
    protocol: {{.protocol}}
    port: {{.port}}
    targetPort: {{.targetPort}}
  {{- end}}
  selector:
  {{- range $key, $value := .selector }}
    {{ $key }}: '{{ $value }}'
  {{- end}}
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
{{- end}}