{{- with $.Values.filebeat}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ $.Values.cluster.namespace }}
  labels:
    k8s-app: filebeat
    app: elasticsearch
    role: filebeat
spec:
  selector:
    matchLabels:
      app: elasticsearch
      role: filebeat
  template:
    metadata:
      labels:
        app: elasticsearch
        role: filebeat
      annotations:  
        co.elastic.metrics/module: beat
        co.elastic.metrics/metricsets: state,stats
        co.elastic.metrics/username: {{ $.Values.sa.username }}
        co.elastic.metrics/password: {{ $.Values.sa.password }}
        
        # co.elastic.monitor/type: "http"
        # co.elastic.monitor/id: ${pod.name}
        # co.elastic.monitor/name: {{ .name }}
        # co.elastic.monitor/schedule: "@every 5s"
        # co.elastic.monitor/hosts: "http://${data.host}:9000/state"
        # co.elastic.monitor/check.response.status: "200"
    spec:
      serviceAccountName: filebeat
      containers:
      - name: filebeat
        image: {{ .image }}:{{ $.Values.cluster.version }}
        args: [
          "-c", 
          "/etc/filebeat.yml",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: cert
            mountPath: /etc/pki/client/
            readOnly: true
          - name: config
            mountPath: /etc/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
      volumes:
      - name: cert
        secret:
          secretName: elasticsearch-cert
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
{{- end }}